# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: torimia_superhero
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - /home/user/JavaProjects/Data:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
    - 6379:6379
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: torimia_user
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: example
      KEYCLOAK_USER: admin1
      KEYCLOAK_PASSWORD: adminadmin
#      KEYCLOAK_LOGLEVEL: DEBUG
    ports:
      - 8082:8080
    depends_on:
      - db
