version: 2.1

orbs:
  maven: circleci/maven@1.1

#workflows:
#  maven_test:
#    jobs:
#      - maven/test
general:
  branches:
    only:
      - master
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: cd Superheroes; mvn package
      - run:
          name: Connecting and deleting older version
          command: ssh ec2-user@ec2-18-184-226-113.eu-central-1.compute.amazonaws.com 'cd ..; cd superhero; sudo rm superheroes-0.0.1-SNAPSHOT.jar'
      - run:
          name: Install new version
          command: scp /target/superheroes-0.0.1-SNAPSHOT.jar ec2-user@ec2-18-184-226-113.eu-central-1.compute.amazonaws.com:/home/superhero
      - run:
          name: Starting server
          command: ssh ec2-user@ec2-18-184-226-113.eu-central-1.compute.amazonaws.com 'java -jar superheroes-0.0.1-SNAPSHOT.jar'